### ISSUE TITLE
Rename "master" to "main"?

### ISSUE THREAD

**Issue by guw** [eclipse/orbit#13]
The term "master" as branch name is deprecated. We should rename to "main".

**Comment by jonahgraham** [comment]
Updated jobs:

- https://ci.eclipse.org/orbit/job/orbit-recipes/jobConfigHistory/showDiffFiles?timestamp1=2023-04-03_10-19-23&timestamp2=2023-05-04_11-33-19
- https://ci.eclipse.org/orbit/job/ebr-maven-plugins/jobConfigHistory/showDiffFiles?timestamp1=2023-03-14_12-24-03&timestamp2=2023-05-04_11-34-22
- https://ci.eclipse.org/orbit/job/orbit-sync-html-files/jobConfigHistory/showDiffFiles?timestamp1=2022-09-30_18-51-36&timestamp2=2023-05-04_11-34-56

Created PRs:

- https://github.com/eclipse/orbit/pull/15
- https://github.com/eclipse/ebr/pull/62
