### ISSUE TITLE
Remove EJML (v0.29) bundles from Orbit

### ISSUE THREAD

**Issue by eselmeister** [eclipse/orbit#19]
A newer version (v0.43) is available here:
http://ejml.org

Furthermore, we faced some problems with conflicting classes when consuming EJML via Orbit. Nowadays, it works fine to reference the EJML dependencies in the product definition by using the Maven dependency option.

If no one else has objections, I will remove the bundles soon.

**Comment by jonahgraham** [comment]
> If no one else has objections, I will remove the bundles soon.

No objection - please go ahead. 

> Nowadays, it works fine to reference the EJML dependencies in the product definition by using the Maven dependency option.

As EJML doesn't seem to have OSGi headers, do you need to coordinate with others to make sure that the OSGi headers match. From a SimRel perspective it doesn't matter as I don't think you contribute EJML to SimRel.

**Comment by merks** [comment]
This seems to have bundle information:

https://repo1.maven.org/maven2/org/ejml/core/0.30/

You're not needing to generate OSGi metadata for any of these things?

**Comment by jonahgraham** [comment]
0.43 doesn't seem to have OSGi here https://repo1.maven.org/maven2/org/ejml/ejml-core/0.43/ - I think they changed artifact Id in 0.31 - https://github.com/lessthanoptimal/ejml/blob/v0.43/change.txt#L419 and the OSGi headers left in 0.39 (side effect of https://github.com/lessthanoptimal/ejml/blob/v0.43/change.txt#L154 as commit https://github.com/lessthanoptimal/ejml/commit/011e9bb1bda0e355c7f25436beab7973b3c29e42 says "- Removed OSGI")

@eselmeister perhaps it is raising an issue with EJML to reenable the headers?

**Comment by eselmeister** [comment]
Yep, we could ask him to do that. I would have to inspect my previous integration of EJML again, but I faintly remember, that there were problems with conflicting imports when using OSGi. Let me have a look at my documents for a detailed answer.
