### ISSUE TITLE
Orbit PMI developer page needs to be updated

### ISSUE THREAD

**Issue by msohn** [eclipse/orbit#22]
https://projects.eclipse.org/projects/tools.orbit/developer mentions that Orbit uses Gerrit linking to http://wiki.eclipse.org/Gerrit.
Later it says the project moved to github.

This should be cleaned up.

I guess we can also remove the note about old versions which were built from CVS which is ancient history not really relevant anymore for today's Orbit contributors.

**Comment by jonahgraham** [comment]
> https://projects.eclipse.org/projects/tools.orbit/developer mentions that Orbit uses Gerrit linking to http://wiki.eclipse.org/Gerrit. Later it says the project moved to github.

The issue with gerrit listed here is that as long as our gerrit orbit repo exists this link is automatic by foundation. I don't want to delete the gerrit instance anytime soon - it is closed for push IIUC - as there is too much valuable history I want to hold onto as long as possible. (I'm still a little bitter that the CVS archives seem lost)

I have asked Webmaster to remove the link without deleting the repo - https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/3171



> 
> I guess we can also remove the note about old versions which were built from CVS which is ancient history not really relevant anymore for today's Orbit contributors.

Done.

**Comment by msohn** [comment]
thanks for the cleanup

Regarding keeping the review history in Gerrit: we plan to move JGit and EGit repos to GerritHub (see https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/3137). When this is accomplished we may consider to also move the historic orbit Gerrit repo there.

**Comment by jonahgraham** [comment]
> When this is accomplished we may consider to also move the historic orbit Gerrit repo there.

And all the other repos too? There is so much valuable history in gerrit for Platform, CDT and others that I think it would be a loss for it to disappear forever.

**Comment by msohn** [comment]
You mean archive the Gerrit history of all those projects read-only on GerritHub ?
I think technically this would be possible, we could discuss this with Luca Milanesio who runs GerritHub.

Our migration ticket where we discuss migration of JGit and EGit to GerritHub/GitHub is here
https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/3137

GerritHub is a combination of Gerrit and Github, reviews happen in Gerrit, changes to be reviewed can either be pushed directly to Gerrit or if a project wants to also support PRs created in Github these PRs can be imported to Gerrit so that they can also be reviewed in Gerrit.

**Comment by akurtakov** [comment]
I have long been advertising that relevant information should be in commits and sources as much as possible in order to minimize such infrastructure changes. I still suffer from code that points to e.g. Jira issues from before being Eclipse project which are no longer available (testTycho123 is totally meaningless nowadays and even confusing as one is not sure whether it's GH issue 123 or old tycho jira 123). Unfortunately, this requires either a change in habbits  - less issues and content in  them or duplicate information.
