### ISSUE TITLE
Bundle version number does not match what's in the GAV

### ISSUE THREAD

**Issue by waynebeaton** [eclipse/orbit#57]
We have two IP review requests created by the Orbit build bot for a bundle ID `com.github.virtuald.curvesapi`. 

e.g., https://gitlab.eclipse.org/eclipsefdn/emo-team/iplab/-/issues/10700

In both cases, the version number of the bundle does not match the version number of the corresponding Maven component.

For example, AFAICT, `com.github.virtuald.curvesapi_1.7.0` maps to `com.github.virtuald:curvesapi:1.07`.

Should I expect that the version numbers align?

**Comment by merks** [comment]
I think this ip lab issue was asking an analogous question so the same information applies:

https://gitlab.eclipse.org/eclipsefdn/emo-team/iplab/-/issues/10729

Here we have a nasty case of Maven version numbers not actually being proper OSGi version numbers.  

Note that this this was subsequently updated to Maven GAV `com.github.virtuald:curvesapi:1.08` with relevant log information is like this:
```
[INFO] Resolving MavenDependencyRoots = [GroupId = com.github.virtuald, ArtifactId = curvesapi, Version = 1.08, ArtifactType = jar, IncludeDependencyScope = ], IncludeDependencyScope = [compile], MissingManifestStrategy = GENERATE, IncludeSource = true
[INFO] default instructions = {Export-Package=*;version="${version}";-noimport:=true, Bundle-SymbolicName=${mvnGroupId}.${mvnArtifactId}, Eclipse-Wrapped-Bundle=${mvnGroupId}:${mvnArtifactId}:${mvnVersion}, Bundle-Version=${version}.v20230927-1624, -noextraheaders=true, -removeheaders=Private-Package, Bundle-Name=Bundle ${mvnGroupId} : ${mvnArtifactId}, version=${versionmask;===;${version_cleanup;${mvnVersion}}}, Import-Package=*;resolution:=optional, Automatic-Module-Name=${mvnGroupId}.${mvnArtifactId}}
[INFO] com.github.virtuald:curvesapi:1.08 is wrapped as a bundle with bundle symbolic name com.github.virtuald.curvesapi
[INFO] The artifact can be referenced in feature files with the following data: <plugin id="com.github.virtuald.curvesapi" version="1.8.0.v20230927-1624" download-size="0" install-size="0" unpack="false"/>
...
[INFO] A review is required for p2/orbit/p2.eclipse.plugin/com.github.virtuald.curvesapi/1.8.0.v20230927-1624.
[INFO] A review request already exists https://gitlab.eclipse.org/eclipsefdn/emo-team/iplab/-/issues/10704 .
```

In the EBR builds it was like this 

https://github.com/eclipse-orbit/orbit/tree/main/github/virtuald/com.github.virtuald.curvesapi_1.6.0

Presumably that was previously reviewed and it's derived from this artifact by the EBR build process:

https://repo1.maven.org/maven2/com/github/virtuald/curvesapi/1.06/curvesapi-1.06.pom

Here the unfortunate version issue also crops up.  This artifact is produced:

https://download.eclipse.org/tools/orbit/downloads/drops/N20230908195041/repository/plugins/com.github.virtuald.curvesapi.source_1.6.0.v20221112-0806.jar
