### ISSUE TITLE
Bundle names do not follow the pattern

### ISSUE THREAD

**Issue by waynebeaton** [eclipse/orbit#58]
Some IPLab issues recently created by the Orbit build bot have bundle IDs that do not match the established pattern.

e.g., https://gitlab.eclipse.org/eclipsefdn/emo-team/iplab/-/issues/10727

The bundle name `org.apache.poi.poi.ooxml` doesn't match the established pattern `org.apache.poi.ooxml` (that is, there is one fewer "poi" in the EBR pattern expressed [here](https://github.com/eclipse-orbit/orbit/blob/main/apache/org.apache.poi.ooxml_4.1.1/pom.xml)).

Is this intentional?

**Comment by merks** [comment]
I think this ip lab issue was asking an analogous question so the same information applies:

https://gitlab.eclipse.org/eclipsefdn/emo-team/iplab/-/issues/10729

In this case, we are again trying to match the previous names ad produced by EBR:

![image](https://github.com/eclipse-orbit/orbit/assets/208716/9628c8f9-4b34-4132-a9bd-d429cec02c4f)

But looking now I see we failed to do that properly:

![image](https://github.com/eclipse-orbit/orbit/assets/208716/d11e1dc0-718f-421a-baa8-54f1dc4115c4)

I'm so glad this was reported before I produced a milestone build!

**Comment by merks** [comment]
These are now in the log:
```
[INFO] A review is required for p2/orbit/p2.eclipse.plugin/org.apache.poi.ooxml/5.2.4.v20230930-1000.
[INFO] A review request was created https://gitlab.eclipse.org/eclipsefdn/emo-team/iplab/-/issues/10769 .
[INFO] A review is required for p2/orbit/p2.eclipse.plugin/org.apache.poi.ooxml.schemas/5.2.4.v20230930-1000.
[INFO] A review request was created https://gitlab.eclipse.org/eclipsefdn/emo-team/iplab/-/issues/10770 .
```

A subsequent build had this:
```
[INFO] A review is required for p2/orbit/p2.eclipse.plugin/org.apache.poi.ooxml/5.2.4.v20230930-1000.
[INFO] A review request was created https://gitlab.eclipse.org/eclipsefdn/emo-team/iplab/-/issues/10771 .
```

I guess a timing (too quick) problem created the duplicates:

- https://gitlab.eclipse.org/eclipsefdn/emo-team/iplab/-/issues/10769 
- https://gitlab.eclipse.org/eclipsefdn/emo-team/iplab/-/issues/10771 

But they were well handled by the review process!
